### ISSUE TITLE
Spell check

### ISSUE THREAD

**Issue by ftrotter** [docgraph/batea_consent#4]
Currently "I am a practicing physician" is misspelled. IT currently reads "practiving".

We need to spell check every page, and fix them all. 

Alma, please spell check the current form, and add the corrections here as a comment...

Then we will either assign them to Alan, or just show you how to use the github interface to fix them directly...

-FT

**Comment by aviars** [comment]
Fred:
I fixed this spelling error and one other I found.
-Alan

```
  From: Fred Trotter <notifications@github.com>
```

 To: docgraph/batea_consent batea_consent@noreply.github.com 
 Sent: Sunday, November 1, 2015 7:44 AM
 Subject: [batea_consent] Spell check (#4)

Currently "I am a practicing physician" is misspelled. IT currently reads "practiving".We need to spell check every page, and fix them all. Alma, please spell check the current form, and add the corrections here as a comment...Then we will either assign them to Alan, or just show you how to use the github interface to fix them directly...-FT—

**Comment by almatrotter** [comment]
Spelling/ Text to fix:

Page 2
2nd sentence needs a period

Page 3 
"completing"misspelled in "Completing optional surveys"
"optional surveys" does not need to be capitalized

Page 4
"clinical" misspelled 2x
All three full sentences need a period
Bullet phrases do not need periods

Page 5
2nd sentence needs period

Page 6
Sentence needs period

Page 7
Current text:
"If you do not want your current browsing session to be uploaded, click the green Batea icon.
This will turn it red, which means it is not recording."

Please update to:
"If you do not want your current browsing session to be uploaded, click the green Batea icon and turn the toggle to the "off" position. 
This will turn the icon red, which means it is not recording."

Page 9 
Sentence needs period

Page 12
Extra space after first parenthesis
Needs space between last bullet point and last sentence

Page 13
Remove comma before "or distracting"

Page 14
"incompetence" misspelled

Page 16
Add the following text above the survey:
"Please take the following quiz to verify that you understand the risks and benefits associated with the Batea Research Study."
