### ISSUE TITLE
Accept and passthrough donator token

### ISSUE THREAD

**Issue by ftrotter** [docgraph/batea_consent#7]
When the consent process is initiated from within the batea extension options page, it will be using a link with a GET variable like so: 

https://batea.docgraph.org/consent/?token=abc123

The consent form needs to pass that token along to the saveSettings API call at the very end along with the results of the survey form.

**Comment by ftrotter** [comment]
I am currently using a config.js file for testing with

CONFIG = {
    postUrl: "https://bateaapi.docgraph.org/API/Donator/abc123/saveSettings"
};

But this file should just be:

CONFIG = {
    postUrl: "https://bateaapi.docgraph.org/"
}

And the rest of the url should be calculated by code... based on the token that was supplied with the initial GET...

**Comment by aviars** [comment]
Hi Fred:  

I'm not sure I fully understand this requirement. the token in your example is "API/Donator/nnnnn144656064895000005187/saveSettings" ?

**Comment by aviars** [comment]
This was addressed by appending all GET params to the JSON document that is submitted, therefore a custom URL does not need to be created for each form submission.
